version: "3.4"
services:
    dsl_example:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./resources/uwsgi.ini:/etc/uwsgi.ini:ro
            - sociallayer_media:/opt/example/media/
            - sociallayer_db:/opt/example/db/
        ports:
            - "8000:8000"
        image: django-social-layer:latest
        
volumes:
    sociallayer_media:
    sociallayer_db:
